################################################################################
# Node-RED Compose
################################################################################
# docker-compose -f docker-compose.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:

  rpi-monitor:
# https://rpi-experiences.blogspot.de/2018/02/rpi-monitor-docker-container.html
# https://github.com/michaelmiklis/docker-rpi-monitor/issues/1
    container_name: myrpimon
    image: michaelmiklis/rpi-monitor
    environment:
      TZ: 'Europe/Vienna'
    network_mode: "service:vpn"
    restart: unless-stopped
    ports:
      - "8888:8888"
    devices:
      - "/dev/vchiq"
      - "/dev/vcs"
    volumes:
      - /opt/vc:/opt/vc/
      - /boot/:/boot/
      - /sys/:/dockerhost/sys/:ro
      - /etc/:/dockerhost/etc/:ro
      - /proc/:/dockerhost/proc/:ro
      - /usr/lib/:/dockerhost/usr/lib/:ro
      - rpimon-data:/var/lib/rpimonitor/stat/

  node-red:
    container_name: mynodered
    build: ./node-red
    command: npm start
    environment:
      TZ: 'Europe/Vienna'
    restart: unless-stopped
    depends_on:
      - vpn
      - mqtt
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

  gpiod:
    image: corbosman/pigpiod
    privileged: true
    restart: unless-stopped

  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-data:/mosquitto
    restart: unless-stopped

  web:
    image: dperson/nginx
    depends_on:
      - node-red
    environment:
      TZ: 'Europe/Vienna'
    links:
      - vpn:node-red
    networks:
      - node-red-net
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: -w "http://node-red:8888;/node-red"
    # service1 shares the network stack of vpn. The service can by reached using
    # the name of the service as a hostname.

volumes:
  rpimon-data:
  node-red-data:
  mqtt-data:

networks:
  node-red-net:
