################################################################################
# Node-RED Compose
################################################################################
# docker-compose -f docker-compose.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  rpi-monitor:
# https://rpi-experiences.blogspot.de/2018/02/rpi-monitor-docker-container.html
# https://github.com/michaelmiklis/docker-rpi-monitor/issues/1
    container_name: myrpimon
    image: michaelmiklis/rpi-monitor
    restart: unless-stopped
    ports:
      - "8888:8888"
    devices:
      - "/dev/vchiq"
      - "/dev/vcs"
    volumes:
      - /opt/vc:/opt/vc/
      - /boot/:/boot/
      - /sys/:/dockerhost/sys/:ro
      - /etc/:/dockerhost/etc/:ro
      - /proc/:/dockerhost/proc/:ro
      - /usr/lib/:/dockerhost/usr/lib/:ro
      - rpimon-data:/var/lib/rpimonitor/stat/

  node-red:
    build: ./node-red
    command: npm start
    environment:
      - TZ=Europe/Vienna
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    restart: unless-stopped
    container_name: mynodered

  gpiod:
    image: corbosman/pigpiod
    privileged: true
    restart: unless-stopped

volumes:
  rpimon-data:
  node-red-data:

networks:
  node-red-net:
